config/routes.rb
CurrencyTracker::Application.routes.draw do
  devise_for :users
  root :to => "currencies#index"
  resources :countries, :except => [:new, :destroy] do
    collection do
      post :visit
    end
  end
  resources :currencies, :only => [:index, :show] do
    collection do
      post :collect
    end
  end

end

app/models/country.rb
class Country < ActiveRecord::Base
  set_primary_key :code
  attr_accessible :name, :code, :visited

  validates_presence_of :name
  validates_presence_of :code
  validates_uniqueness_of :code, :allow_blank => true
  has_many :currencies
  accepts_nested_attributes_for :currencies, :allow_destroy => true
  
  scoped_search :on => [:name, :code]
  
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  set_primary_key :code
  attr_accessible :name, :code, :country_id

  validates_presence_of :name
  validates_presence_of :code
  validates_uniqueness_of :code, :allow_blank => true

  belongs_to :country
  
  scoped_search :on => [:name, :code]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :login, :password, :password_confirmation, :remember_me
  has_many :user_countries do
    def visited
      where(:visited => true)
    end
  end
  
  def visited_countries_hash
    Hash[user_countries.map{|item| [item.country_id, item]}]
  end
  
  def collected_currencies_hash
    Hash[user_countries.map{|item| [item.currency_id, item]}]
  end
    
end

app/models/user_country.rb
class UserCountry < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  belongs_to :currency
  
  validates :currency_id, :uniqueness => {:scope => [:user_id, :country_id]}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  helper_method :visited_countries_count, :not_visited_countries_count, :collected_countries_count, :not_collected_countries_count
  
  def visited_countries_count
    current_user.user_countries.visited.count(:country_id, :distinct => true)
  end
  
  def not_visited_countries_count
    Country.count - visited_countries_count
  end
  
  def collected_countries_count
    current_user.user_countries.visited.count
  end
  
  def not_collected_countries_count
    Currency.count - collected_countries_count
  end
  
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    @countries = Country.search_for(params[:q])
    @user_countries = current_user.visited_countries_hash
    if request.xhr?
      render :partial => 'list', :layout => false
    end
  end
  
  def visit
    if request.xhr?
      begin
        countries = Country.where(:code => params[:country]).joins(:currencies).map do |country|
          country.code if country.currencies.map do |currency|
            current_user.user_countries.create(:visited => true, :currency_id => currency.code, :country_id => country.code)
          end.size > 0
        end
      rescue => e
        raise e
        render :json => e.backtrace.join("\n").to_json, :status => :unprocessable_entity
      else
        render :json => {:countries => countries, :uncheck => (params[:country] - countries),:visited => visited_countries_count, :not_visited => not_visited_countries_count}.to_json, :status => :ok
      end
    else
      redirect_to :action => :index
    end
  end
  
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  # GET /currencies
  # GET /currencies.xml
  def index
    @currencies = Currency.search_for(params[:q])
    @user_currencies = current_user.collected_currencies_hash
    if request.xhr?
      render :partial => 'list', :layout => false
    end
  end
  
  def collect
    if request.xhr?
      begin
        Currency.where(:code => params[:currency]).joins(:country).each do |currency|
          current_user.user_countries.create(:visited => true, :currency_id => currency.code, :country_id => currency.country.code)
        end
      rescue
        render :json => {}.to_json, :status => :unprocessable_entity
      else
        render :json => {:collected => params[:currency], :visited => visited_countries_count, :not_visited => not_visited_countries_count}.to_json, :status => :ok
      end
    else
      redirect_to :action => :index
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_list.html.erb
<%= form_tag collect_currencies_path, :remote => true, :id => 'collect-currencies-form' do %>
<table>
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th>Status</th>
    <th><%= submit_tag 'Collect', :disable_with => 'Collecting...' %></th>
  </tr>
  <% @currencies.each do |currency| %>
  <% visited = @user_currencies[currency.code] && @user_currencies[currency.code].visited? %>
    <tr>
      <td><%= currency.name %></td>
      <td><%= currency.code %></td>
      <td id="currency_status_<%= currency.code %>"><%= visited ? 'Collected' : 'Not Collected' %></td>
      <td><%= check_box_tag 'currency[]', currency.code, visited, :id => %Q(currency_code_#{currency.code}), :disabled => visited %></td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/currencies/index.html.erb
<section>
  <div id="collected_currencies_chart" class="simple_pie_chart" width='300px' height='100px'>
    <table>
      <tr>
        <th>Collected</th>
        <td><%= collected_countries_count %></td>
      </tr><tr>
        <th>Not Collected</th>
        <td><%= not_collected_countries_count %></td>
      </tr>
    </table>
  </div>
  <div id="collected_currencies_line_chart" class="simple_line_chart" width='300px' height='100px'>
    <table>
      <% current_user.user_countries.visited.group('DATE(created_at)').count.each do |item| %>
        <tr>
          <th><%= item[0] %></th>
          <td><%= item[1] %></td>
        </tr>
      <% end %>
    </table>
  </div>

  <h1>Currencies</h1>
  <br/>
  <br/>
  <br/>
  <%= form_tag currencies_path, :remote => true, :class => 'filter-form', :'data-type' => 'html', :'data-container' => '#currencies-list', :method => :get do %>
    <%= text_field_tag 'q', params[:q], :placeholder => 'Filter keyword' %>
  <% end %>
  <button class="select-all" data-container="#currencies-list">Select All</button>
  <br/>
  <br/>
  <div id="currencies-list">
    <%= render :partial => 'list' %>
  </div>
</section>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @currency.name %>
</p>

<p>
  <b>Code:</b>
  <%= @currency.code %>
</p>

<p>
  <b>Status:</b>
  <%= @currency.collected? ? 'Collected' : 'Not Collected' %>
</p>

<p>
  <b>Country:</b>
  <%= @currency.country.nil? ? 'None' : link_to(@currency.country.name, @currency.country) %>
</p>

<%= link_to 'Back', currencies_path %>